# Generated by Django 4.2.2 on 2023-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="birthday",
            field=models.DateField(blank=True, default=None, verbose_name="birthday"),
        ),
    ]
