# Generated by Django 4.2.2 on 2023-07-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0002_alter_profileuser_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="birthday",
            field=models.DateField(default=None, null=True, verbose_name="birthday"),
        ),
    ]
