# Generated by Django 4.2.2 on 2023-07-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0003_alter_profileuser_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="about",
            field=models.CharField(max_length=128, null=True, verbose_name="about"),
        ),
    ]
