# Generated by Django 4.2.2 on 2023-07-15 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0006_comment_created_at_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
    ]
