# Generated by Django 4.2.2 on 2023-07-15 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0007_remove_post_dislikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
    ]
