# Generated by Django 4.2.2 on 2023-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0008_remove_comment_dislikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="post_comments", to="profileapp.comment"
            ),
        ),
    ]
