# Generated by Django 4.2.2 on 2023-07-15 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0009_remove_comment_post_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="warned",
            field=models.ManyToManyField(
                blank=True, related_name="comment_warned", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="warned",
            field=models.ManyToManyField(
                blank=True, related_name="post_warned", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
