# Generated by Django 4.2.2 on 2023-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0010_comment_warned_post_warned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="img",
            field=models.ImageField(
                blank=True, default="none", upload_to="users/avatars"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(
                blank=True, default="none", upload_to="users/avatars"
            ),
        ),
    ]
