# Generated by Django 4.2.2 on 2023-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0014_alter_comment_img_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="comments/"),
        ),
    ]
