# Generated by Django 4.2.2 on 2023-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequests",
            name="ban_time",
        ),
        migrations.RemoveField(
            model_name="userrequests",
            name="is_banned",
        ),
        migrations.RemoveField(
            model_name="userrequests",
            name="request_time",
        ),
        migrations.AddField(
            model_name="userrequests",
            name="request_started",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="request_time"
            ),
        ),
        migrations.AlterField(
            model_name="userrequests",
            name="ip",
            field=models.CharField(max_length=30, unique=True, verbose_name="ip"),
        ),
        migrations.AlterField(
            model_name="userrequests",
            name="request_count",
            field=models.IntegerField(default=1, verbose_name="request_count"),
        ),
    ]
