# Generated by Django 4.2.2 on 2023-07-27 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_remove_userrequests_ban_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRequests",
            new_name="UserRequest",
        ),
    ]
